### ISSUE TITLE
SDL support

### ISSUE THREAD

**Issue by szymor** [xu4-engine/u4#17]
Is SDL support planned? I see there is some code for that, though the build fails with:
`
event_sdl.cpp:117:14: error: ‘SDL_MOUSEWHEEL’ was not declared in this scope; did you mean ‘IE_MOUSE_WHEEL’?
`

If it is planned, it would be nice to have support for legacy SDL (i.e. SDL1). I would love to see this game on some cheap handhelds and SDL1 is a prerequisite for that.

**Comment by WickedSmoke** [comment]
The SDL1 backend works in version 1.0 but it has not been maintained since then.  Newer versions use OpenGL, so some changes would be needed to restore pure bitmap rendering.  That's not on my roadmap so someone else would have to take on that task.

**Comment by szymor** [comment]
OK, thank you for the quick and accurate answer.
